query:
  name: "Query AI Agent with Home Assistant context"
  description: "Run a custom AI prompt against your Home Assistant state dump."
  fields:
    prompt:
      description: "The question or instruction to send to the AI model."
      example: "Turn on all the lights in the living room"
