query:
  name: "Query AI with Home Assistant context"
  description: "Run a custom prompt against your selected AI provider."
  fields:
    prompt:
      description: "The question or instruction to send to the AI model."
      example: "Which rooms have lights on?"
    provider:
      description: "The AI provider to use (openai, llama, gemini, openrouter)"
      example: "openai"
      default: "openai"
      selector:
        select:
          options:
            - "openai"
            - "llama"
            - "gemini"
            - "openrouter"
